### ISSUE TITLE
Initial list

### ISSUE THREAD

**Issue by mxstbr** [styled-components/polished#1]
Below is a list of helpers we think would be useful to have in this toolset. A few notes before diving in and implementing them:

- We are aiming for 100% test coverage, so extensively test the utils you write
- Add helpful error messages and type checking based on the util @bhough will write in #4 
- These helpers should be method agnostic, i.e. not `styled-components` specific. This means they need to return css-in-js, by which I mean JavaScript objects, not CSS strings.

An example what `ellipsis` could return:

```JS
const Box = styled.div`
  ${ ellipsis('250px') }
`
```

```JS
{
  // Value from first argument
  width: '250px',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}
```

> Note that `styled-components` can handle simple styles as JavaScript objects perfectly fine, except you can't have pseudo-selectors and those sorts of things in the objects. We'll have to have a discussion what to do with the more complex of these helpers!

By returning objects, these also work for any CSS-in-JS method:

```JS
const styles = {
  ...ellipsis('250px'),
}
```

🎉

**Mixins**

- [x] Clearfix (@bhough, #22 )
- [x] Ellipsis (@bhough, #17)
- [x] Font Face (@bhough, #63)
- [x] Hide Text (@bhough, #19)
- [x] HiDPI Media Query (@bhough, #22)
- [x] Placeholder (@bhough, #42)
- [x] Radial Gradient (@bhough, #66)
- [x] Reset/Normalize (@bhough. #67)
- [x] Retina Image (@mxstbr, #50)
- [x] Selection (@bhough, #41)
- [x] Timing Functions (@bhough, #20)
- [x] Triangle (@machycek, #77)
- [x] Word Wrap (@mxstbr, #16)

**Shorthands**

- [x] Animation (@mxstbr, #29)
- [x] Background (@bhough, #64)
- [x] Background Image (@bhough, #64)
- [x] Border-Color (@bhough, #56)
- [x] Border-Radius (@bhough, #68)
- [x] Border-Style (@bhough, #56)
- [x] Border-Width (@bhough, #56)
- [x] Buttons (@bhough, #57)
- [x] Inputs (@bhough, #57)
- [x] Margin (@bhough, #56)
- [x] Padding (@bhough, #56)
- [x] Position (@bhough, #56)
- [x] Transition (@bhough, #65)
- [x] Size (@bhough, #43)

**Helpers**

- [x] px to em (@mxstbr, #34)
- [x] px to rem (@mxstbr, #35 )
- [x] directional properties (@bhough, #56)
- [x] ~~golden ratio~~ modular scale (@mxstbr, #45)
- [x] strip units (@bhough, #18)

**Color**

RGB

- [x] RGB (@nikgraf, #53)
- [x] RGBA (@nikgraf, #62 )
- [x] mix (@nikgraf)

HSL

- [x] hsl (@nikgraf, #70)
- [x] hsla (@nikgraf, #74)
- [x] adjustHue (@nikgraf)
- [x] lighten (@nikgraf)
- [x] darken (@nikgraf)
- [x] saturate (@nikgraf)
- [x] desaturate (@nikgraf)
- [x] grayscale (@nikgraf)
- [x] complement (@nikgraf)
- [x] invert (@nikgraf)

Opacity

- [x] rgba
- [x] opacify (@nik)
- [x] transparentize (@nik)

Misc

- [x] shade (@bhough #100)
- [x] tint (@bhough #100)

**Comment by ericclemmons** [comment]
What'd be helpful (for me) is editing the list, as exhaustive as it is, with suggested usage examples so that way individuals can tackle & submit PRs more effectively.

Or, if we want to do the TDD thing, the first step would be tests for the use cases that someone else would implement :)

I think a lot of these would be handled by wrapping [color](https://www.npmjs.com/package/color), but likely with a better `.toString` implementation or functional underpinnings.

(On that note, I personally find `color`'s fluent interface much clearer than nested function calls that you see nowadays)

**Comment by mxstbr** [comment]
Good point, added an example to the OC! Right now we're still setting up and figuring out how we want to do this, so I don't think implementing a helper right now is a good idea?

**Comment by ericclemmons** [comment]
Fair enough.  I know we've been creating ad-hoc versions of these internally, but it seems that the majority of the color-related functions could be solved by recommending/supporting the stringification of objects from libs like `color` & `chroma.js`:

> http://gka.github.io/chroma.js/

That leaves "mixins" as the only one not really answered here, which I think warrants solving within this project.  The others can be referenced via documentation & be effectively "solved" from the user's standpoint.

**Comment by bhough** [comment]
@ericclemmons what are some examples of mixins we are missing from this? We are purposely excluding ones that only return prefixes as most CSS in JS solutions included prefixers built in. I also don't believe we need to include the concept of mixin creation as you see in SASS/LESS as in JS those are just normal functions.

**Comment by ericclemmons** [comment]
Frankly, I've found I'm mostly lacking a good `reset` / `normalize` & something akin to:
> https://github.com/maximkoretskiy/postcss-autoreset

When testing our React components with this across browsers & sites, there's been a lot of "bleed-through" of parent styles & browser inconsistencies that had us like, "Wait, I thought this was a solved problem?"

We're so used to these tools leveling the browser playing field.

**Comment by ericclemmons** [comment]
Wait a tick, shouldn't we all just be using @kyleamathews' http://kyleamathews.github.io/typography.js/!?

**Comment by mxstbr** [comment]
I would like all of these utils to live under a single package with the same API for all of those, like Bourbon does for Sass.

Having to search for all of those packages individually and having to learn their complete different APIs seems very backwards for me, and is something that (as we've noticed in our issue tracker) not many people do, even though that's their reason for not switching to styles in JS yet.

Not sure how `typography.js` is related?

**Comment by ericclemmons** [comment]
@mxstbr Sorry, let me clarify:

- Of course it would be ideal for `polished` to "own" the API for these utils.  **However**, until the solution exists, a bit of documentation could go a long way to answer users' needs instead of them _writing off this project because it doesn't have a built-in solution yet_.
- We agree that the intent is _not_ to rebuild `color` or `chroma.js` ourselves, but to wrap other libs as necessary to provide a clean API (e.g. Bourbon).
- I mentioned `typograph.js` erroneously.  I thought it had useful utils/normalization that we could leverage, but it's pretty much a "select a theme & eject the CSS" project.


Anyway, I'm working on a project right now with `styled-components` that could use media & normalization mixins.  I'd like to have those built internally in a way they could be applied here.

**Comment by KyleAMathews** [comment]
@ericclemmons you're underselling typography.js a bit :-) The "themes" aren't the point, they're a byproduct. One way of viewing it is as a global styles reset with a high-level API focused on typographic design. For my projects I put all global styles in Typography.js and then component styles in components and this combo works really well together.

Anyways, a Lodash for css-in-js sounds freaking amazing! Will be following along closely!

**Comment by mxstbr** [comment]
Ah, now I get what you're saying @ericclemmons. Yeah, I totally agree with that, though this project isn't announced/official yet and probably won't be until we have all utils of the initial list finished. 👍

**Comment by KyleAMathews** [comment]
A utility for link styles would be great — text-underline, box-shadow, border-bottom, and the cool effect where descenders cover the link — https://eager.io/blog/smarter-link-underlines/

**Comment by KyleAMathews** [comment]
And on converting between css size units — I wrote this (used in Typography.js) https://github.com/KyleAMathews/convert-css-length

**Comment by mxstbr** [comment]
> I wrote this (used in Typography.js) https://github.com/KyleAMathews/convert-css-length

Coffeescript 🙈

Just kidding, looks great! Let's rewrite it in ES6 and export it from `polished`!

**Comment by KyleAMathews** [comment]
Haha :-)

Sounds great! Would love to move things here!

**Comment by KyleAMathews** [comment]
I can make a PR soonish.

**Comment by mxstbr** [comment]
Awesome, sounds great! We just finished setting up the automatic documentation and the testing stuff 👌

**Comment by garetmckinley** [comment]
> Note that styled-components can handle simple CSS-in-JS perfectly fine. It doesn't handle pseudo-selectors and those sorts of things though, so we'll have to have a discussion what to do with the more complex of these helpers!

What pseudo-selectors does `styled-components` not support? It's worked with a lot of the things I've thrown at it.

I was happy to see complex things like

```jsx
import styled from 'styled-components';
import { Link } from 'react-router';

const A = styled(Link)`
  color: #000;
  text-decoration: underline;
  &::before {
    content: '💩';
  }
  &::after {
    content: '🍺';
  }
  &:hover {
    opacity: .2;
    &::before, &::after {
      content: '😻';
    }
  }
`;

export default A;
```

functioning as expected. I don't think I could get the `:visited` selector to work though. Although I'm to sure why `:hover` would work and `:visited` would not, do they require manually written transformers or something?

I feel like the most often used pseudo-selectors are `::before`, `::after`, and `:hover`, so it's good that they work 👏

**Comment by Dattaya** [comment]
> I don't think I could get the :visited selector to work though

It depends on what you were trying to do, `:visited` pseudo class [has some limitations](https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector#Limits_to_visited_link_styles).

**Comment by garetmckinley** [comment]
Wow, I had no idea there were that many constraints on the `:visited` selector. So no chance of updating a pseudo-element of a `:visited` selector?

**Comment by mxstbr** [comment]
> What pseudo-selectors does styled-components not support? It's worked with a lot of the things I've thrown at it.

It supports all of them, but it doesn't support them in object notation, just as a CSS string, that's what I was trying to say. Will update the comment to reflect that better!

**Comment by mxstbr** [comment]
We should just use this instead of adding all the functions manually, 👏 @rofrishmann! https://github.com/cssinjs/css-functions

**Comment by mxstbr** [comment]
As for lighten/darken I found this SO answer: https://stackoverflow.com/questions/5560248/programmatically-lighten-or-darken-a-hex-color-or-rgb-and-blend-colors#13542669

Anybody want to dig into that? 🙈

**Comment by garetmckinley** [comment]
Oooo that looks like fun. I may give it a go tomorrow

**Comment by bhough** [comment]
Removing `flexbox` and `keyframes` as they are unnecessary with a autoprefixer.

**Comment by nikgraf** [comment]
@bhough @mxstbr I'm going to implement these next

- adjustHue(degrees, color)
- grayscale(color)
- complement(color)
- invert(color)
- opacify(color)
- transparentize(color)
- mix(color1, color2)
- tint(amount, color) (is it the same as lighten?)
- shade(amount, color) (is it the same as darken?)

These function don't make much sense since they only provide a single value of function. Do you guys think this is valuable? I would suggested we drop the following ones and add them later if there are valid use-cases.

- hue(color) - Gets the hue component of a color.
- saturation(color) - Gets the saturation component of a color.
- lightness(color) - Gets the lightness component of a color.
- alpha($color) / opacity($color) - Gets the alpha component (opacity) of a color.
- red(color)
- green(color)
- blue(color)

Thoughts?

**Comment by mxstbr** [comment]
Sounds good to me @nikgraf! I reckon when we got these and I'll finally finish the website (submitting a WIP PR soon) we can release this :shipit:

**Comment by bhough** [comment]
I've been in the process of moving, but I'm also done with the error handler as well as integrating it into existing modules. I should have something to share by Monday.

**Comment by mxstbr** [comment]
`v1.0.0` is out! :tada: Amazing job everybody!
