### ISSUE TITLE
V3 Roadmap

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#354]
- [x] toColorString performance improvements (likely based on #187).
- [x] update readableColor to return a custom color instead of just black or white.
- [x] color modules safely handle the `transparent` keyword.
- [x] linear gradient mixin.
- [X] modularScale accepts rem for its base value.
- [x] Math helper for doing operations on values with units.
- [x] Improved errors/validation in development, and stripped with links in production.
- [x] Mark `getUnitAndValue` for deprecation.
- [x] Update `stripUnit` to optionally return the unit that was removed.
- [x] Deprecate selection mixin.
- [x] Deprecate placeholder mixin.

_final_

**Comment by TrySound** [comment]
`sideEffects` is not used by rollup. Pure annotations are used by uglify.

**Comment by brunolemos** [comment]
Maybe re-add the contrast ratio function? I don't see it on the list.

#206 #302 #305 #394

**Comment by bhough** [comment]
@brunolemos https://github.com/styled-components/polished/blob/version-3/src/color/readableColor.js

**Comment by brunolemos** [comment]
Hm, that's more like a sugar for one specific use case, but it's not really a `getContrastRatio` function.

There seems to be a standard for this, the ratio is a number and there's level AA or AAA.
Check https://contrast-ratio.com/

The chrome element style tool works the same way: 

![image](https://user-images.githubusercontent.com/619186/52411084-a19d3500-2ac1-11e9-928c-1f3f6f5839a5.png)

https://developers.google.com/web/fundamentals/accessibility/accessible-styles#color_and_contrast

https://webaim.org/resources/contrastchecker/

**Comment by bhough** [comment]
Understand the use case @brunolemos. Mostly pointing out that most of the issues/PRs you pointed to were resolved by the modifications to `readableColor`. `getContrast` was not something we have ever had and would be a new feature. Happy to accept it as a feature request.

**Comment by brunolemos** [comment]
Ah ok. Seems to be #394 then.
