### ISSUE TITLE
Polished Roadmap

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#397]
# v4.0.0

## New Modules
- [x] **Important Helper** - Add a helper for adding important flags to existing modules.
- [ ] **CSS Logical Properties** - Add a mixin for leveraging logical properties with proper fallbacks.

## Module Improvements
- [x] **`ellipsis`** - add support for multiline ellipsis.
- [x] **`fontFace`** - add local font file checking to avoid unnecessarily downloading remote font.
- [ ] **Color Modules** - optimize HSL(A) color detection to avoid converting and recovering hsl values.
- [x] **`timingFunctions`** - separate timing functions into their own modules.
- [x] **`cssVar`** - allow default values to be passed when a value is not found for a css-variable

## Other Improvements
- [x] **Test Rewrite** - Rewrite testing to use specific expect statements instead of snapshot tests.
- [ ] **Integration Testing** - Adding integration testing with `styled-components` and `emotion` and in browser and non-browser environments.

## Bug Fixes
- [x] **`fluidRange`** - currently does not work with REMs, we will be investigating why this is breaking and attempt to provide support for REMs/EMs.
- [x] **`triangle`** - restore the ability to leverage `inherit`.

## Breaking Changes
- [ ] **Make presets optional** - Several of our modules leverage large preset objects to provide commonly used values. The majority of users don't leverage these, yet everyone takes the bundle size hit for them. In v4, we will re-working those modules to take these as optional imports and providing a way for users to provide additional presets. This includes a variety of color modules and the `math` module.
- [x] **`stripUnit`** - After much discussion, we will be keeping `getValueAndUnit` and returning `stripUnit` to its previous functionality. This makes the functionality the same as the named method, simplifies typing (that we previously had to make very forgiving), and keeps the more commonly used method smaller. **Therefore, the return unit functionality in `stripUnit` will be deprecated in v4.
- [x] **`readableColor`** - strict mode will become the default behavior in v4 and will need to be explicitly turned off to use non-contrast-compliant return colors.

## Other
We will be revamping the contributor experience. This will include simplifying the build, leveraging GitHub functionality to make it easier to contribute and make feature requests, starting a support Slack, among other things.

_Updated as of 8/18/2020_

**Comment by wtgtybhertgeghgtwtg** [comment]
In regards to the third bullet point (and please let me know if I should raise this in another issue instead), would that include integrating it as a macro, as `styled-components` does?

**Comment by bhough** [comment]
@wtgtybhertgeghgtwtg It would be a separate ask, but certainly something we'd be open to doing.

**Comment by oliviertassinari** [comment]
Bundle size would be great. We have private color helpers on Material-UI side. People ask us to expose them. I was curious to see if we could drop them for polished: https://github.com/mui-org/material-ui/pull/15540.

**Comment by bhough** [comment]
@oliviertassinari Reach out on that PR. Would love to work with you to allow you to use polished for this, especially if it is just a matter of working on bundle size.

**Comment by el1f** [comment]
**Regarding point 3: docs redesign**
I was wondering whether that's still up for grabs? I'd love to take a spin at designing a new doc for this lib :)

**Comment by ricokahler** [comment]
There were a few discussions on bundle size here so I thought I would share.

I recently released [`color2k`](https://color2k.com) which is a color lib I built specifically to have a [small bundle size](https://bundlephobia.com/result?p=color2k) (1.5kB).

The big secret there is to [use canvas](https://github.com/ricokahler/color2k/blob/master/packages/parse-to-rgba/src/index.ts) to parse colors to rgba. This removes the need for larger files like [`_nameToHex`](https://github.com/styled-components/polished/blob/master/src/internalHelpers/_nameToHex.js) and streamlines conversions to other color types (e.g. always parse to rgba then to any other color format).

There's definitely some tradeoffs with approach, namely [parsing speed](https://github.com/ricokahler/parse-to-rgba#why-not-canvas) and an extra node [compatibility package](https://github.com/ricokahler/color2k/tree/master/packages/node) but I think these tradeoffs are worth it. Hopes this piques your interest!

---

P.S. Thanks for polished! [color2k wouldn't exist without it.](https://github.com/ricokahler/color2k#credits)

**Comment by oliviertassinari** [comment]
@ricokahler Smart! Would it support colors outside the the sRGB color space, for instance https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/?

**Comment by ricokahler** [comment]
@oliviertassinari Thanks! I answered your question over here 👆because it's off topic in this thread
